services:
  gcc-lab:
    image: cpp-reflection-lab:gcc
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp-reflection-lab-gcc
    stdin_open: true
    tty: true
    volumes:
      - ./examples:/examples
    environment:
      - CXX=g++
